name: Android Game Test

on: [push, pull_request]

jobs:
  test-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 7zip
        run: sudo apt-get install p7zip-full

      - name: Extract Game Files
        run: 7z x apk/Shadow_Ops.7z.001 -oapk/

      #- name: Debug SDK Path
       # run: echo $ANDROID_HOME && ls -R $ANDROID_HOME
        
      - name: Set Up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          
          # Create correct SDK folder structure
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
      
          # Export environment variables
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
      
          # Accept licenses and install necessary components
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;default;x86_64"



      - name: Create and Start Emulator
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
      
          # Debugging: Check if avdmanager exists
          ls -l $ANDROID_HOME/cmdline-tools/latest/bin/
      
          # Create Emulator (Ensure avdmanager works)
          yes "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-30;default;x86_64" --device "pixel"
      
          # Start Emulator in Background
          nohup $ANDROID_HOME/emulator/emulator -avd test_emulator -no-snapshot -no-audio -no-window -gpu swiftshader_indirect &


      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Install APK
        run: adb install apk/Shadow_Ops.apk

      - name: Launch Game
        run: adb shell monkey -p com.yourcompany.shadowops -c android.intent.category.LAUNCHER 1

      - name: Interact with Game (Simulate Tap)
        run: adb shell input tap 500 1000

      - name: Capture Logcat
        run: adb logcat -d > logcat.txt

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logcat
          path: logcat.txt
