name: Android APK Test

on:
  push:
    branches:
      - main

jobs:
  test-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 7-Zip
        run: sudo apt-get install p7zip-full -y

      - name: Extract APK
        run: 7z x Shadow_Ops.7z.001 -oextracted_apk

      - name: Verify APK Extraction
        run: ls -lah extracted_apk

      - name: Run Prebuilt Emulator and Test APK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86
          profile: pixel_4
          disable-animations: true
          script: |
            adb install extracted_apk/Shadow_Ops.apk
            adb shell monkey -p com.example.shadowops -c android.intent.category.LAUNCHER 1
            sleep 10  # Give app time to render
            adb exec-out screencap -p > screenshot.png

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: apk-screenshot
          path: screenshot.png
