name: Android Emulator Setup

on:
  push:
    branches:
      - main

jobs:
  run-android-emulator:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 7-Zip
        run: choco install 7zip

      - name: Extract APK from 7z Archive
        run: |
          7z x Shadow_Ops.7z.001 -oextracted_apk

      - name: Set Up Android SDK
        run: |
          echo "Downloading Android Command Line Tools..."
          Invoke-WebRequest -Uri "https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip" -OutFile "cmdline-tools.zip"
          Expand-Archive cmdline-tools.zip -DestinationPath "C:\Android\cmdline-tools"

          # Find actual extracted folder name
          Get-ChildItem -Path "C:\Android\cmdline-tools" | ForEach-Object { echo "Found: $_.Name" }

          # Move extracted folder into expected structure
          $extractedFolder = Get-ChildItem -Path "C:\Android\cmdline-tools" | Where-Object { $_.Name -match "cmdline-tools" } | Select-Object -ExpandProperty Name
          if ($extractedFolder) {
            Move-Item -Path "C:\Android\cmdline-tools\$extractedFolder" -Destination "C:\Android\cmdline-tools\latest" -Force
          } else {
            echo "Error: Command line tools folder not found!"
            exit 1
          }



      - name: Configure Environment Variables
        run: |
          echo "ANDROID_HOME=C:\Android" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ANDROID_SDK_ROOT=C:\Android" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "C:\Android\cmdline-tools\latest\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\Android\platform-tools" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Install Android SDK & Emulator
        run: |
          sdkmanager --sdk_root=C:\Android --install "platform-tools" "platforms;android-30" "system-images;android-30;default;x86_64" "emulator"
          avdmanager create avd -n test_emulator -k "system-images;android-30;default;x86_64" --force

      - name: Start Emulator
        run: |
          echo "Starting Emulator..."
          emulator -avd test_emulator -no-window -no-audio -no-boot-anim &

      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82
        timeout-minutes: 5

      - name: Install APK on Emulator
        run: |
          adb install extracted_apk/Shadow_Ops.apk

      - name: Verify APK Installation
        run: adb shell pm list packages | findstr "shadow_ops"
