name: Android Emulator Test

on:
  push:
    branches:
      - main

jobs:
  run-android-emulator:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 7-Zip
        run: choco install 7zip

      - name: Extract APK from 7z Archive
        run: |
          7z x Shadow_Ops.7z.001 -oextracted_apk

      - name: Install Android SDK & Emulator
        run: |
          echo "y" | sdkmanager --install "system-images;android-30;default;x86"
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-30;default;x86"

      - name: Start Emulator
        run: |
          echo "Starting Emulator..."
          emulator -avd test_emulator -no-window -no-audio -no-boot-anim &

      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82
        timeout-minutes: 5

      - name: Install APK on Emulator
        run: |
          adb install extracted_apk/Shadow_Ops.apk

      - name: Verify APK Installation
        run: adb shell pm list packages | findstr "shadow_ops"
