name: Android Emulator Setup

on:
  push:
    branches:
      - main

jobs:
  run-android-emulator:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 7-Zip
        run: choco install 7zip

      - name: Extract APK from 7z Archive
        run: |
          7z x Shadow_Ops.7z.001 -oextracted_apk

      - name: Set Up Android SDK
        run: |
          echo "Downloading Android Command Line Tools..."
          Invoke-WebRequest -Uri "https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip" -OutFile "cmdline-tools.zip"
          Expand-Archive cmdline-tools.zip -DestinationPath "C:\Android"

          # Ensure correct folder structure
          if (-Not (Test-Path "C:\Android\cmdline-tools\latest")) {
            New-Item -ItemType Directory -Path "C:\Android\cmdline-tools\latest"
          }

          # Move extracted files into the latest folder
          Get-ChildItem -Path "C:\Android\cmdline-tools" -Exclude "latest" | Move-Item -Destination "C:\Android\cmdline-tools\latest" -Force


      - name: Configure Environment Variables
        run: |
          echo "ANDROID_HOME=C:\Android" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ANDROID_SDK_ROOT=C:\Android" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "C:\Android\cmdline-tools\latest\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\Android\platform-tools" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\Android\emulator" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Install Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Accept Android SDK Licenses
        run: |
          echo y | C:\Android\cmdline-tools\latest\bin\sdkmanager.bat --licenses

      - name: Install Android SDK & Emulator
        run: |
          C:\Android\cmdline-tools\latest\bin\sdkmanager.bat --sdk_root=C:\Android --install "platform-tools" "platforms;android-30" "system-images;android-30;default;x86_64" "emulator"
          C:\Android\cmdline-tools\latest\bin\avdmanager.bat create avd -n test_emulator -k "system-images;android-30;default;x86_64" --force

      - name: Start Emulator
        run: |
          echo "Starting Emulator..."
          emulator -avd test_emulator -no-window -no-audio -no-boot-anim &

      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82
        timeout-minutes: 5

      - name: Install APK on Emulator
        run: |
          adb install extracted_apk/Shadow_Ops.apk

      - name: Verify APK Installation
        run: adb shell pm list packages | findstr "shadow_ops"
