name: Run APK Game in Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 (required for Android SDK tools)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Install 7zip to extract the APK
      - name: Install 7zip
        run: sudo apt-get install p7zip-full -y

      # Extract the APK from the 7z archive
      - name: Extract APK
        run: |
          7z x apk/Shadow_Ops.7z.001 -oapk/extracted
          ls apk/extracted # List extracted files for debugging

      # Start Android emulator
      - name: Run Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30 # Android API level (e.g., 30 for Android 11)
          arch: x86_64 # Emulator architecture
          profile: Nexus 6 # Device profile
          script: |
            adb devices # List connected devices
            adb install apk/extracted/Shadow_Ops.apk # Install the APK
            adb shell am start -n com.example.game/.MainActivity # Launch the game

      # Upload extracted APK (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: apk/extracted/Shadow_Ops.apk
