name: Android APK Test

on:
  push:
    branches:
      - main

jobs:
  test-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 7-Zip
        run: sudo apt-get install p7zip-full -y

      - name: Extract APK
        run: 7z x Shadow_Ops.7z.001 -oextracted_apk

      - name: Verify APK Extraction
        run: ls -lah extracted_apk

      - name: Install Android SDK & Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O android_cmdline.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip android_cmdline.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Install Required Android Components
        run: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-31" "emulator" "system-images;android-31;default;x86_64"
          sleep 10  # Give time for installation to complete

      - name: Manually Create AVD Directory (Fix Missing Issue)
        run: mkdir -p $HOME/.android/avd

      - name: Create AVD
        run: |
          export ANDROID_AVD_HOME=$HOME/.android/avd
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-31;default;x86_64" --device "pixel_4" --force
          ls -lah $HOME/.android/avd/

      - name: Verify AVD Exists
        run: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          avdmanager list avd
          ls -lah $HOME/.android/avd/

      - name: Start Emulator
        run: |
          export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH
          nohup emulator -avd test_emulator -no-audio -no-window -gpu swiftshader_indirect -no-boot-anim &

      - name: Wait for Emulator to Boot
        run: |
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Install APK on Emulator
        run: adb install extracted_apk/Shadow_Ops.apk

      - name: Launch APK
        run: adb shell monkey -p com.example.shadowops -c android.intent.category.LAUNCHER 1

      - name: Capture Screenshot
        run: adb exec-out screencap -p > screenshot.png

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: apk-screenshot
          path: screenshot.png
