name: Android APK Test

on:
  push:
    branches:
      - main

jobs:
  test-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 7-Zip
        run: sudo apt-get install p7zip-full -y

      - name: Extract APK
        run: 7z x Shadow_Ops.7z.001 -oextracted_apk

      - name: Verify APK Extraction
        run: ls -lah extracted_apk

      - name: Install Android SDK & Emulator
        uses: android-actions/setup-android@v3

      - name: Install System Image
        run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-31;default;x86_64"

      - name: Create AVD
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list avd
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-31;default;x86_64" --device "pixel_4" --force
          echo "AVD Created Successfully"

      - name: Verify AVD Exists
        run: $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list avd

      - name: Start Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -list-avds
          nohup $ANDROID_HOME/emulator/emulator -avd test_emulator -no-audio -no-window -gpu swiftshader_indirect &

      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Install APK on Emulator
        run: adb install extracted_apk/Shadow_Ops.apk

      - name: Launch APK
        run: adb shell monkey -p com.example.shadowops -c android.intent.category.LAUNCHER 1

      - name: Capture Screenshot
        run: adb exec-out screencap -p > screenshot.png

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: apk-screenshot
          path: screenshot.png
