name: Run APK Game in Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Install 7zip to extract the APK
      - name: Install 7zip
        run: sudo apt-get install p7zip-full -y

      # Extract the APK from the 7z archive
      - name: Extract APK
        run: |
          7z x apk/Shadow_Ops.7z.001 -oapk/extracted
          ls apk/extracted # List extracted files for debugging

      # Start ADB server
      - name: Start ADB server
        run: adb start-server

      # Run Android emulator
      - name: Run Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          script: |
            adb devices
            adb install apk/extracted/Shadow_Ops.apk
            adb shell am start -n com.example.game/.MainActivity
          disable-animations: true
          disable-hw-accel: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -accel off -no-snapshot -no-snapshot-save
          boot-timeout: 600

      # Capture emulator logs (for debugging)
      - name: Capture emulator logs
        run: |
          adb logcat -d > emulator.log
          cat emulator.log

      # Upload extracted APK (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: apk/extracted/Shadow_Ops.apk
