name: Cache Downloaded File

on: [push, pull_request]

jobs:
  download_and_cache:
    runs-on: windows-latest

    steps:
      - name: Cache Downloads
        id: cache-download
        uses: actions/cache@v4
        with:
          path: downloads
          key: download-cache

      - name: Create Downloads Folder
        if: steps.cache-download.outputs.cache-hit != 'true'
        run: mkdir downloads
        shell: pwsh

      - name: Download File
        if: steps.cache-download.outputs.cache-hit != 'true'
        run: Invoke-WebRequest "https://ak-build.bluestacks.com/public/app-player/windows/nxt/5.22.0.1102/05d8f0c866456671405d769a653cb88d/FullInstaller/x64/BlueStacksFullInstaller_5.22.0.1102_amd64_native.exe" -OutFile "downloads/blue.exe"
        shell: pwsh