name: Cache Blue Folder

on:
  workflow_dispatch:

jobs:
  cache-blue:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Blue Folder (If Missing)
        run: |
          if not exist blue mkdir blue
          echo Cached content > blue\example.txt

      - name: Save "blue" Folder to Cache
        uses: actions/cache@v3
        with:
          path: blue
          key: blue-${{ github.sha }}