name: Restore and List Cached Downloads

on: 
    workflow_dispatch:  


jobs:
  restore_and_list:
    runs-on: windows-latest

    steps:
      - name: Restore Cache
        id: cache-download
        uses: actions/cache@v4
        with:
          path: downloads
          key: download-cache

      - name: List Cached Files
        if: steps.cache-download.outputs.cache-hit == 'true'
        run: Get-ChildItem -Path downloads
        shell: pwsh
