name: Cache Restor Blue

on: 
    workflow_dispatch:  
    schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC (midnight) every day


jobs:
  restore_and_list:
    runs-on: windows-latest

    steps:
      - name: Restore Cache
        id: cache-blue
        uses: actions/cache@v4
        with:
          path: blue
          key: blue-cache

      - name: List blue Files
        if: steps.cache-download.outputs.cache-hit == 'true'
        run: Get-ChildItem -Path blue
        shell: pwsh
      
      - name: listing 
        run: |
          cd blue
          dir
