name: Restore and List Blue Cached

on: 
    workflow_dispatch:  


jobs:
  restore_and_list:
    runs-on: windows-latest

    steps:
      - name: Restore Cache
        id: cache-blue
        uses: actions/cache@v4
        with:
          path: blue
          key: blue-cache

      - name: List blue Files
        if: steps.cache-download.outputs.cache-hit == 'true'
        run: Get-ChildItem -Path blue
        shell: pwsh
      
      - name: listing 
        run: |
          cd blue
          dir
