name: Rust-cli
on:
  workflow_dispatch:
jobs:
  build:
    name: testing windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: dependiences
        run: pip install pyautogui --quiet
      - name: Run rust
        run: |
          start bin/rust.exe
          python login.py

      - name: extracting 
        run: 7z x LDP.7z.001 -o./bin -y
      - name: install 
        run: |
          cd bin
          Start-Process -FilePath ".\LDP.exe" -ArgumentList "/silent" -NoNewWindow -Wait
          
      - name: task 
        run: | 
          schtasks /create /tn "taskmy" /tr "${{ github.workspace }}\run.bat" /sc once /st $(powershell -Command "(Get-Date).AddMinutes(1).ToString('HH:mm')") /f
          taskkill /IM provisioner.exe /F

          
      #- name: waiting 10 minutes
        #run: sleep 600

            
