name: Rust-cli
on:
  workflow_dispatch:
jobs:
  build:
    name: testing windows-latest
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: dependiences
        run: pip install pyautogui --quiet

      - name: Extract APK from 7z Archive
        run: |
          7z x Shadow_Ops.7z.001 -oextracted_apk
          dir extracted_apk  # Verify APK is extracted
    
      - name: Run rust
        run: |
          start bin/rust.exe
          python login.py

      - name: task 
        run: | 
          schtasks /create /tn "taskmy" /tr "${{ github.workspace }}\run.bat" /sc once /st $(powershell -Command "(Get-Date).AddMinutes(1).ToString('HH:mm')") /f
          taskkill /IM provisioner.exe /F

          
      #- name: waiting 10 minutes
        #run: sleep 600

            
