name: BLS-5-ad-monitor
on:
  workflow_dispatch:
jobs:
  build:
    name: windows
    runs-on: windows-latest
    steps:
       
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      
      - name: Cache "blue" Folder
        uses: actions/cache@v3
        with:
            path: blue
            key: blue-${{ github.sha }}
            restore-keys: |
                blue-

      - name: Extract blue
        run: 7z x blue/blue.7z.001 -oblue

      - name: Dependiences
        run: pip install -r requirements.txt
        
      
      - name: Setup Applicition and APK
        run: python setup.py

      - name: Run rust
        run: |
          start bin/rust.exe
          python login.py  

      - name: Test Python Blue 
        run: python blue.py